#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
#
# 这份配置已为您量身定制，旨在提供更现代、更个性化的博客体验。
# 您可以根据需要随时调整这些设置。
#---------------------------


#---------------------------
# 全局
# Global
#---------------------------

# 用于浏览器标签的图标
# Icon for browser tab
favicon: /img/fluid.png

# 用于苹果设备的图标
# Icon for Apple touch
apple_touch_icon: /img/fluid.png

# 浏览器标签页中的标题分隔符，效果： 文章名 | 站点名
# Title separator in browser tab, eg: article | site
tab_title_separator: " | "

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
# Force all links to be HTTPS (applicable to HTTP mixed error)
force_https: false

# 代码块的增强配置
# Enhancements to code blocks
code:
  # 是否开启复制代码的按钮
  # Enable copy code button
  copy_btn: true

  # 代码语言
  # Code language
  language:
    enable: true
    default: "TEXT"

  # 代码高亮
  # Code highlight
  highlight:
    enable: true

    # 代码块是否显示行号
    # If true, the code block display line numbers
    line_number: true

    # 实现高亮的库，对应下面的设置
    # Highlight library
    # Options: highlightjs | prismjs
    lib: "highlightjs"

    highlightjs:
      # 挑选了更现代和清晰的代码高亮风格
      style: "atom-one-light"
      style_dark: "atom-one-dark"

    prismjs:
      style: "default"
      style_dark: "tomorrow night"
      preprocess: true

# 一些好玩的功能
# Some fun features
fun_features:
  # 为 subtitle 添加打字机效果，只在首页开启
  # Typing animation for subtitle, only on home page
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    # 动画只播放一次
    loop: false
    # 只在首页开启
    scope: [home]

  # 为文章内容中的标题添加锚图标，方便分享和跳转
  # Add an anchor icon to the title on the post page for easy navigation
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    # 图标显示在标题右侧
    placement: right
    # 悬停时才显示，使页面更整洁
    visible: hover
    icon: ""

  # 加载进度条
  # Progress bar when loading
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    options: { showSpinner: false, trickleSpeed: 100 }

# 主题暗色模式，开启后菜单中会出现切换按钮
# Theme dark mode. If enable, a switch button will appear on the menu
dark_mode:
  enable: true
  # 优先遵循用户系统设置，其次根据时间自动切换
  default: auto

# 主题颜色配置，挑选了更柔和、现代的配色方案
# Theme color, selected a softer, more modern color scheme
color:
  body_bg_color: "#f0f2f5"
  body_bg_color_dark: "#1e1e1e"

  navbar_bg_color: "#ffffff"
  navbar_bg_color_dark: "#2c2c2c"

  navbar_text_color: "#4a5568"
  navbar_text_color_dark: "#e2e8f0"

  subtitle_color: "#2d3748"
  subtitle_color_dark: "#cbd5e0"

  text_color: "#2d3748"
  text_color_dark: "#c4c6c9"

  sec_text_color: "#718096"
  sec_text_color_dark: "#a0aec0"

  board_color: "#ffffff"
  board_color_dark: "#2c2c2c"

  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"

  post_heading_color: "#1a202c"
  post_heading_color_dark: "#e2e8f0"

  post_link_color: "#3182ce"
  post_link_color_dark: "#63b3ed"

  link_hover_color: "#2b6cb0"
  link_hover_color_dark: "#90cdf4"

  link_hover_bg_color: "#f7fafc"
  link_hover_bg_color_dark: "#4a4a4a"

  line_color: "#e2e8f0"
  line_color_dark: "#4a4a4a"

  scrollbar_color: "#cbd5e0"
  scrollbar_color_dark: "#5c5c5c"
  scrollbar_hover_color: "#a0aec0"
  scrollbar_hover_color_dark: "#8d8d8d"

  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"
  button_hover_bg_color: "#edf2f7"
  button_hover_bg_color_dark: "#3a3a3a"

# 主题字体配置
# Font
font:
  font_size: 16px
  font_family:
  letter_spacing: 0.02em
  code_font_size: 85%

# 指定自定义 .js 文件路径，用法和 custom_css 相同
custom_js:

# 指定自定义 .css 文件路径，用法和 custom_js 相同
custom_css:

# 网页访问统计
web_analytics:
  enable: false
  follow_dnt: true
  baidu:
  google:
    measurement_id:
  tencent:
    sid:
    cid:
  woyaola:
  cnzz:
  leancloud:
    app_id:
    app_key:
    server_url:
    path: window.location.pathname
    ignore_local: false

# 对页面中的图片和评论插件进行懒加载处理
# Lazy loading of images and comment plugin on the page
lazyload:
  enable: true
  loading_img: /img/loading.gif
  # 懒加载仅在文章页生效以提高性能
  onlypost: true
  offset_factor: 2

# 图标库
iconfont: //at.alicdn.com/t/font_1736178_lbnruvf0jn.css


#---------------------------
# 页头
# Header
#---------------------------

# 导航栏的相关配置
# Navigation bar
navbar:
  # 导航栏左侧的标题，设为您自己的博客名
  blog_title: "TanZp"
  # 开启毛玻璃特效
  ground_glass:
    enable: true
    px: 5
    alpha: 0.8
  # 导航栏菜单
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

# 搜索功能
search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: post
  content: true

# 首屏图片的相关配置
banner:
  parallax: true
  width_height_ratio: 1.0

# 向下滚动的箭头
scroll_down_arrow:
  enable: true
  banner_height_limit: 80
  scroll_after_turning_page: true

# 向顶部滚动的箭头
scroll_top_arrow:
  enable: true

# Open Graph metadata
open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:


#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  # 页脚第一行文字的 HTML，为您定制了更简洁的文字
  content: '
    <a href="https://tanzipeng.github.io" target="_blank" rel="nofollow noopener"><span>TanZp</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://tanzipeng.github.io" target="_blank" rel="nofollow noopener"><span>ShuaiGe</span></a>
  '
  # 展示网站的 PV、UV 统计数，使用 busuanzi 简单易用
  statistics:
    enable: true
    source: "busuanzi"
  # 国内大陆服务器的备案信息
  beian:
    enable: false
    icp_text:
    police_text:
    police_code:
    police_icon:


#---------------------------
# 首页
# Home Page
#---------------------------
index:
  # 首页 Banner 头图，您需要准备一张名为 `home-banner.png` 的图片并放在 `source/img/` 目录下
  banner_img: /img/home-banner.png
  banner_img_height: 100
  banner_mask_alpha: 0.4
  # 首页副标题的独立设置
  slogan:
    enable: true
    # 个性化副标题，您可以根据喜好修改
    text: "Exploring the world, one line of code at a time."
    api:
      enable: false
      url: ""
      method: "GET"
      headers: {}
      keys: []
  # 自动截取文章摘要
  auto_excerpt:
    enable: true
  # 打开文章的标签方式，在当前窗口打开
  post_url_target: _self
  # 显示文章信息（时间、分类、标签）
  post_meta:
    date: true
    category: true
    tag: true
  # 置顶文章的图标
  post_sticky:
    enable: true
    icon: "iconfont icon-top"


#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  # 文章页头图，您需要准备一张名为 `post-banner.png` 的图片并放在 `source/img/` 目录下
  banner_img: /img/default-cover.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
  # 文章在首页的默认封面图
  default_index_img: /img/default-cover.png
  # 文章标题下方的元信息
  meta:
    author:
      enable: false
    date:
      enable: true
      format: "YYYY-MM-DD HH:mm:ss"
    wordcount:
      enable: true
    min2read:
      enable: true
      awl: 2
      wpm: 60
    # 开启浏览量计数，使用 busuanzi
    views:
      enable: true
      source: "busuanzi"
  # 在文章开头显示更新时间，以相对时间形式展示
  updated:
    enable: true
    date_format: "LL"
    relative: true
    note_class: info
  # 侧边栏展示当前分类下的文章
  category_bar:
    enable: true
    specific: false
    placement: left
    post_order_by: "title"
    post_limit: 0
  # 侧边栏展示文章目录
  toc:
    enable: true
    placement: right
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapseDepth: 0
  # 版权声明，使用 'BY-NC-SA' 许可证
  copyright:
    enable: true
    license: 'BY-NC-SA'
    author:
      enable: true
    post_date:
      enable: true
      format: "YYYY-MM-DD"
    update_date:
      enable: false
      format: "YYYY-MM-DD"
  # 文章底部上一篇下一篇功能
  prev_next:
    enable: true
  # 文章图片标题
  image_caption:
    enable: true
  # 文章图片可点击放大
  image_zoom:
    enable: true
    img_url_replace: ['', '']
  # 脚注语法
  footnote:
    enable: true
    header: ''
  # 数学公式和流程图默认关闭，如果需要使用，可以手动开启
  math:
    enable: false
    specific: false
    engine: mathjax
  mermaid:
    enable: false
    specific: false
    options: { theme: 'default' }
  # 评论插件默认关闭，如果您需要开启，请在 `comments` 下方配置您选择的插件
  comments:
    enable: false
    type: disqus


#---------------------------
# 评论插件
#---------------------------
utterances:
  repo:
  issue_term: pathname
  label: utterances
  theme: github-light
  theme_dark: github-dark

disqus:
  shortname:
  disqusjs: false
  apikey:

gitalk:
  clientID:
  clientSecret:
  repo:
  owner:
  admin: ['name']
  language: zh-CN
  labels: ['Gitalk']
  perPage: 10
  pagerDirection: last
  distractionFreeMode: false
  createIssueManually: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token

valine:
  appId:
  appKey:
  path: window.location.pathname
  placeholder:
  avatar: 'retro'
  meta: ['nick', 'mail', 'link']
  requiredFields: []
  pageSize: 10
  lang: 'zh-CN'
  highlight: false
  recordIP: false
  serverURLs: ''
  emojiCDN:
  emojiMaps:
  enableQQ: false

waline:
  serverURL: ''
  path: window.location.pathname
  meta: ['nick', 'mail', 'link']
  requiredMeta: ['nick']
  lang: 'zh-CN'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
  dark: 'html[data-user-color-scheme="dark"]'
  wordLimit: 0
  pageSize: 10

changyan:
  appid: ''
  appkey: ''

livere:
  uid: ''

remark42:
  host:
  site_id:
  max_shown_comments: 10
  locale: zh
  components: ['embed']

twikoo:
  envId:
  region: ap-shanghai
  path: window.location.pathname

cusdis:
  host:
  app_id:
  lang: zh-cn

giscus:
  repo:
  repo-id:
  category:
  category-id:
  theme-light: light
  theme-dark: dark
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  input-position: top
  lang: zh-CN

discuss:
  serverURLs:
  path: window.location.pathname


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3


#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 10


#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  # 您的头像和介绍
  avatar: /img/avatar.png
  name: "TanZp"
  intro: "An elegant theme for Hexo"
  # 社交媒体图标，已为您保留 GitHub 和微信，并添加了 Twitter 选项
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com", tip: "GitHub" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }
    - { class: "iconfont icon-twitter", link: "https://twitter.com", tip: "Twitter" }


#---------------------------
# 自定义页
# Custom Page
#---------------------------
page:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 85
  banner_mask_alpha: 0.3
  redirect_delay: 5000


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  items:
    - {
      title: "Fluid Blog",
      intro: "主题博客",
      link: "https://hexo.fluid-dev.com/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Docs",
      intro: "主题使用指南",
      link: "https://hexo.fluid-dev.com/docs/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Repo",
      intro: "主题 GitHub 仓库",
      link: "https://github.com/fluid-dev/hexo-theme-fluid",
      avatar: "/img/favicon.png"
    }
  onerror_avatar: /img/avatar.png
  custom:
    enable: false
    content: '<hr><p>在下方留言申请加入我的友链，按如下格式提供信息：</p><ul><li>博客名：Fluid</li><li>简介：Fluid 主题官方博客</li><li>链接：https://hexo.fluid-dev.com</li><li>图片：https://hexo.fluid-dev.com/img/favicon.png</li></ul>'
  comments:
    enable: false
    type: disqus


#---------------------------
# 以下是配置 JS CSS 等静态资源的 URL 前缀，可以自定义成 CDN 地址
# DO NOT EDIT THE FOLLOWING SETTINGS UNLESS YOU KNOW WHAT YOU ARE DOING
#---------------------------

static_prefix:
  internal_js: /js
  internal_css: /css
  internal_img: /img
  anchor: https://lib.baomitu.com/anchor-js/4.3.1/
  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/
  jquery: https://lib.baomitu.com/jquery/3.6.4/
  bootstrap: https://lib.baomitu.com/twitter-bootstrap/4.6.1/
  prismjs: https://lib.baomitu.com/prism/1.29.0/
  tocbot: https://lib.baomitu.com/tocbot/4.20.1/
  typed: https://lib.baomitu.com/typed.js/2.0.12/
  fancybox: https://lib.baomitu.com/fancybox/3.5.7/
  nprogress: https://lib.baomitu.com/nprogress/0.2.0/
  mathjax: https://lib.baomitu.com/mathjax/3.2.2/
  katex: https://lib.baomitu.com/KaTeX/0.16.2/
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/
  clipboard: https://lib.baomitu.com/clipboard.js/2.0.11/
  mermaid: https://lib.baomitu.com/mermaid/8.14.0/
  valine: https://lib.baomitu.com/valine/1.5.1/
  waline: https://cdn.staticfile.org/waline/2.15.5/
  gitalk: https://lib.baomitu.com/gitalk/1.8.0/
  disqusjs: https://lib.baomitu.com/disqusjs/1.3.0/
  twikoo: https://lib.baomitu.com/twikoo/1.6.8/
  discuss: https://lib.baomitu.com/discuss/1.2.1/
  hint: https://lib.baomitu.com/hint.css/2.7.0/
  moment: https://lib.baomitu.com/moment.js/2.29.4/
