#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# A guide to customizing this theme: https://hexo.fluid-dev.com/docs/en/guide/
#
# This configuration has been customized to provide a clean and modern blogging experience.
# Feel free to adjust these settings to fit your personal style.
#---------------------------


#---------------------------
# Global
#---------------------------

# Icon for browser tab and Apple devices
favicon: /img/fluid.png
apple_touch_icon: /img/fluid.png

# Title separator for browser tabs
tab_title_separator: " | "

# Force all links to be HTTPS (useful for mixed content errors)
force_https: false

# Enhancements to code blocks
code:
  # Enable copy code button
  copy_btn: true

  # Code language display
  language:
    enable: true
    default: "TEXT"

  # Code highlighting
  highlight:
    enable: true
    # Display line numbers in code blocks
    line_number: true
    # Highlight library: highlightjs or prismjs
    lib: "highlightjs"
    highlightjs:
      # A clean, modern style for light and dark modes
      style: "atom-one-light"
      style_dark: "atom-one-dark"

# Fun features to enhance user experience
fun_features:
  # Typing animation for the subtitle on the homepage
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    # The animation will play only once
    loop: false
    # This effect will only be enabled on the homepage
    scope: [home]

  # Add an anchor icon to post headings for easy linking
  anchorjs:
    enable: true
    # Apply to all heading levels
    element: h1,h2,h3,h4,h5,h6
    # Place the icon to the right of the heading
    placement: right
    # Only show the icon on hover for a cleaner look
    visible: hover
    # The default icon is usually fine, so we'll leave it empty
    icon: ""

  # Loading progress bar at the top of the page
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    options: { showSpinner: false, trickleSpeed: 100 }

# Theme dark mode switch
dark_mode:
  enable: true
  # Automatically switch between light and dark based on the user's system preferences
  default: auto

# Theme color configuration for a cohesive design
color:
  body_bg_color: "#f0f2f5"
  body_bg_color_dark: "#1e1e1e"

  navbar_bg_color: "#ffffff"
  navbar_bg_color_dark: "#2c2c2c"

  navbar_text_color: "#2d3748"
  navbar_text_color_dark: "#e2e8f0"

  # === 重点调整这里，提高深色模式下标题和元信息的对比度 ===
  subtitle_color: "#2d3748"
  subtitle_color_dark: "#f8f8f8" # 从 #cbd5e0 调整为更亮的 #f8f8f8

  text_color: "#2d3748"
  text_color_dark: "#e0e0e0" # 统一提高暗色模式下的主要文本亮度

  sec_text_color: "#4a5568"
  sec_text_color_dark: "#cccccc" # 统一提高暗色模式下的次要文本亮度

  board_color: "#ffffff"
  board_color_dark: "#2c2c2c"

  post_text_color: "#1a202c"
  post_text_color_dark: "#e0e0e0" # 统一提高暗色模式下的文章正文亮度

  post_heading_color: "#1a202c"
  post_heading_color_dark: "#f8f8f8" # 从 #e2e8f0 调整为更亮的 #f8f8f8

  post_link_color: "#3182ce"
  post_link_color_dark: "#63b3ed"

  link_hover_color: "#2b6cb0"
  link_hover_color_dark: "#90cdf4"

  link_hover_bg_color: "#f7fafc"
  link_hover_bg_color_dark: "#4a4a4a"

  line_color: "#e2e8f0"
  line_color_dark: "#4a4a4a"

  scrollbar_color: "#cbd5e0"
  scrollbar_color_dark: "#5c5c5c"
  scrollbar_hover_color: "#a0aec0"
  scrollbar_hover_color_dark: "#8d8d8d"

  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"
  button_hover_bg_color: "#edf2f7"
  button_hover_bg_color_dark: "#3a3a3a"

# Font configuration
font:
  font_size: 16px
  font_family:
  letter_spacing: 0.02em
  code_font_size: 85%

# Custom JS and CSS files
custom_js:
custom_css:

# Web analytics
web_analytics:
  enable: false
  # Follow "Do Not Track" setting
  follow_dnt: true
  baidu:
  google:
    measurement_id:
  tencent:
    sid:
    cid:
  woyaola:
  cnzz:
  leancloud:
    app_id:
    app_key:
    server_url:
    path: window.location.pathname
    ignore_local: false

# Lazy loading for images and comments
lazyload:
  enable: true
  loading_img: /img/loading.gif
  # Only enable lazyload on post pages for better performance
  onlypost: true
  offset_factor: 2

# Icon library
iconfont: //at.alicdn.com/t/font_1736178_lbnruvf0jn.css


#---------------------------
# Header
#---------------------------

# Navigation bar
navbar:
  # Blog title for the navigation bar
  blog_title: "TanZp"
  # Frosted glass effect for the navigation bar
  ground_glass:
    enable: true
    px: 5
    alpha: 0.8
  # Navigation bar menu items
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    #- { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

# Search feature
search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: post
  content: true

# Banner image settings
banner:
  # Scrolling parallax effect for the banner
  parallax: true
  width_height_ratio: 1.0

# Scroll down arrow
scroll_down_arrow:
  enable: true
  banner_height_limit: 80
  scroll_after_turning_page: true

# Scroll to top arrow
scroll_top_arrow:
  enable: true

# Open Graph metadata
open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:


#---------------------------
# Footer
#---------------------------
footer:
  # Customized footer content
  content: '
    <a href="https://tanzipeng.github.io" target="_blank" rel="nofollow noopener"><span>TanZp</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://tanzipeng.github.io" target="_blank" rel="nofollow noopener"><span>ShuaiGe</span></a>
  '
  # Website statistics
  statistics:
    enable: true
    # Use busuanzi for simplicity and no extra configuration
    source: "busuanzi"
  # Chinese mainland website policy info
  beian:
    enable: false
    icp_text:
    police_text:
    police_code:
    police_icon:


#---------------------------
# Home Page
#---------------------------
index:
  banner_img: /img/default.png
  banner_img_height: 100
  banner_mask_alpha: 0.4
  slogan:
    enable: true
    # A more personal subtitle
    text: "Exploring the world, one line of code at a time."
    api:
      enable: false
      url: ""
      method: "GET"
      headers: {}
      keys: []
  auto_excerpt:
    enable: true
  post_url_target: _self
  # Display post metadata on the homepage
  post_meta:
    date: true
    category: true
    tag: true
  post_sticky:
    enable: true
    icon: "iconfont icon-top"


#---------------------------
# Post Page
#---------------------------
post:
  banner_img: /img/default.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
  default_index_img:
  meta:
    author:
      enable: false
    date:
      enable: true
      format: "YYYY-MM-DD HH:mm:ss"
    wordcount:
      enable: true
    min2read:
      enable: true
      awl: 2
      wpm: 60
    views:
      enable: true
      source: "busuanzi"
  updated:
    enable: true
    date_format: "LL"
    relative: true
    note_class: info
  category_bar:
    enable: true
    specific: false
    placement: left
    post_order_by: "title"
    post_limit: 0
  toc:
    enable: true
    placement: right
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapseDepth: 0
  copyright:
    enable: true
    license: 'BY-NC-SA'
    author:
      enable: true
    post_date:
      enable: true
      format: "YYYY-MM-DD"
    update_date:
      enable: false
      format: "YYYY-MM-DD"
  prev_next:
    enable: true
  image_caption:
    enable: true
  image_zoom:
    enable: true
    img_url_replace: ['', '']
  footnote:
    enable: true
    header: ''
  math:
    enable: false


#---------------------------
# Comment plugins
#
# Enable comments: post: comments: enable: true
#---------------------------

utterances:
  repo:
  issue_term: pathname
  label: utterances
  theme: github-light
  theme_dark: github-dark

disqus:
  shortname:
  disqusjs: false
  apikey:

gitalk:
  clientID:
  clientSecret:
  repo:
  owner:
  admin: ['name']
  language: zh-CN
  labels: ['Gitalk']
  perPage: 10
  pagerDirection: last
  distractionFreeMode: false
  createIssueManually: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token

valine:
  appId:
  appKey:
  path: window.location.pathname
  placeholder:
  avatar: 'retro'
  meta: ['nick', 'mail', 'link']
  requiredFields: []
  pageSize: 10
  lang: 'zh-CN'
  highlight: false
  recordIP: false
  serverURLs: ''
  emojiCDN:
  emojiMaps:
  enableQQ: false

waline:
  serverURL: ''
  path: window.location.pathname
  meta: ['nick', 'mail', 'link']
  requiredMeta: ['nick']
  lang: 'zh-CN'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
  dark: 'html[data-user-color-scheme="dark"]'
  wordLimit: 0
  pageSize: 10

changyan:
  appid: ''
  appkey: ''

livere:
  uid: ''

remark42:
  host:
  site_id:
  max_shown_comments: 10
  locale: zh
  components: ['embed']

twikoo:
  envId:
  region: ap-shanghai
  path: window.location.pathname

cusdis:
  host:
  app_id:
  lang: zh-cn

giscus:
  repo:
  repo-id:
  category:
  category-id:
  theme-light: light
  theme-dark: dark
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  input-position: top
  lang: zh-CN

discuss:
  serverURLs:
  path: window.location.pathname


#---------------------------
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3


#---------------------------
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 10


#---------------------------
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "TanZp"
  intro: "An elegant theme for Hexo"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com", tip: "GitHub" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }
    - { class: "iconfont icon-twitter", link: "https://twitter.com", tip: "Twitter" }


#---------------------------
# Custom Page
#---------------------------
page:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3


#---------------------------
# 404 Page
#---------------------------
page404:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 85
  banner_mask_alpha: 0.3
  redirect_delay: 5000


#---------------------------
# Links Page
#---------------------------
links:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  items:
    - {
      title: "Fluid Blog",
      intro: "主题博客",
      link: "https://hexo.fluid-dev.com/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Docs",
      intro: "主题使用指南",
      link: "https://hexo.fluid-dev.com/docs/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Repo",
      intro: "主题 GitHub 仓库",
      link: "https://github.com/fluid-dev/hexo-theme-fluid",
      avatar: "/img/favicon.png"
    }
  onerror_avatar: /img/avatar.png
  custom:
    enable: false
    content: '<hr><p>在下方留言申请加入我的友链，按如下格式提供信息：</p><ul><li>博客名：Fluid</li><li>简介：Fluid 主题官方博客</li><li>链接：https://hexo.fluid-dev.com</li><li>图片：https://hexo.fluid-dev.com/img/favicon.png</li></ul>'
  comments:
    enable: false
    type: disqus


#---------------------------
# Static assets prefix
#---------------------------
static_prefix:
  internal_js: /js
  internal_css: /css
  internal_img: /img
  anchor: https://lib.baomitu.com/anchor-js/4.3.1/
  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/
  jquery: https://lib.baomitu.com/jquery/3.6.4/
  bootstrap: https://lib.baomitu.com/twitter-bootstrap/4.6.1/
  prismjs: https://lib.baomitu.com/prism/1.29.0/
  tocbot: https://lib.baomitu.com/tocbot/4.20.1/
  typed: https://lib.baomitu.com/typed.js/2.0.12/
  fancybox: https://lib.baomitu.com/fancybox/3.5.7/
  nprogress: https://lib.baomitu.com/nprogress/0.2.0/
  mathjax: https://lib.baomitu.com/mathjax/3.2.2/
  katex: https://lib.baomitu.com/KaTeX/0.16.2/
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/
  clipboard: https://lib.baomitu.com/clipboard.js/2.0.11/
  mermaid: https://lib.baomitu.com/mermaid/8.14.0/
  valine: https://lib.baomitu.com/valine/1.5.1/
  waline: https://cdn.staticfile.org/waline/2.15.5/
  gitalk: https://lib.baomitu.com/gitalk/1.8.0/
  disqusjs: https://lib.baomitu.com/disqusjs/1.3.0/
  twikoo: https://lib.baomitu.com/twikoo/1.6.8/
  discuss: https://lib.baomitu.com/discuss/1.2.1/
  hint: https://lib.baomitu.com/hint.css/2.7.0/
  moment: https://lib.baomitu.com/moment.js/2.29.4/